// Generated by `wit-bindgen` 0.19.1. DO NOT EDIT!
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Diagnostics;

namespace MarkdownWorld.wit.exports.pizza4dotnet.example.v0_1_0;

public interface IConverter {
    static abstract string ToHtml(string markdown);
    
}

