// Generated by `wit-bindgen` 0.19.1. DO NOT EDIT!
#ifndef __BINDINGS_GREETER_H
#define __BINDINGS_GREETER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} greeter_string_t;

// Imported Functions from `pizza4dotnet:example/converter@0.1.0`
extern void pizza4dotnet_example_converter_to_html(greeter_string_t *markdown, greeter_string_t *ret);

// Exported Functions from `pizza4dotnet:example/greeting@0.1.0`
void exports_pizza4dotnet_example_greeting_greet(greeter_string_t *name, greeter_string_t *ret);

// Helper Functions

// Transfers ownership of `s` into the string `ret`
void greeter_string_set(greeter_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void greeter_string_dup(greeter_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void greeter_string_free(greeter_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
