// Generated by `wit-bindgen` 0.19.1. DO NOT EDIT!
#include "greeter.h"


__attribute__((__import_module__("pizza4dotnet:example/converter@0.1.0"), __import_name__("to-html")))
extern void __wasm_import_pizza4dotnet_example_converter_to_html(int32_t, int32_t, int32_t);
__attribute__((__weak__, __export_name__("cabi_post_pizza4dotnet:example/greeting@0.1.0#greet")))
void __wasm_export_exports_pizza4dotnet_example_greeting_greet_post_return(int32_t arg0) {
  if ((*((int32_t*) (arg0 + 4))) > 0) {
    free((void*) (*((int32_t*) (arg0 + 0))));
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void greeter_string_set(greeter_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void greeter_string_dup(greeter_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void greeter_string_free(greeter_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

void pizza4dotnet_example_converter_to_html(greeter_string_t *markdown, greeter_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_pizza4dotnet_example_converter_to_html((int32_t) (*markdown).ptr, (int32_t) (*markdown).len, ptr);
  *ret = (greeter_string_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

__attribute__((__export_name__("pizza4dotnet:example/greeting@0.1.0#greet")))
int32_t __wasm_export_exports_pizza4dotnet_example_greeting_greet(int32_t arg, int32_t arg0) {
  greeter_string_t arg1 = (greeter_string_t) { (uint8_t*)(arg), (size_t)(arg0) };
  greeter_string_t ret;
  exports_pizza4dotnet_example_greeting_greet(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

extern void __component_type_object_force_link_greeter(void);
void __component_type_object_force_link_greeter_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_greeter();
}
