// Generated by `wit-bindgen` 0.19.1. DO NOT EDIT!
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Diagnostics;

namespace HostWorld {
    
    public interface IHostWorld {
    }
    
    public static class InteropString
    {
        public static IntPtr FromString(string input, out int length)
        {
            var utf8Bytes = Encoding.UTF8.GetBytes(input);
            length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            return gcHandle.AddrOfPinnedObject();
        }
    }
    
}
